name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: borales/actions-yarn@v4
      with:
          cmd: --frozen-lockfile install

    - name: Install puppeteer libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm1
        
    - name: Run and test app
      run: |
        npm run start &
        npm run test

    - name: Build
      run: npm run build
      env: 
        CI: false

    # deploy the react app to github pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        # NOTE: GITHUB_TOKEN is a secret token that is automatically generated by GitHub
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build # directory to deploy



    
